buddypress/BP-REST

- bp-rest.php
- includes/bp-groups/classes/class-bp-groups-endpoints.php
First pass at allowing fetching of groups using REST. Fetches single
groups and collections of groups using an argument format much like
`groups_get_groups()`.
Still need to work out accepting meta arguments and also visibility of hidden groups.
How are we going to test all of this REST stuff?
Finally, is the REST `context` parameter really a security thing? It appears to be used that way in the main plugin, but I'm doubtful. I've used it here to make `populate_extras` only be possible with the context elevation, but it's still really a view context with increased user permissions, so maybe that's incorrect.
> Group READABLE endpoint

- bp-rest.php
- includes/bp-members/bp-members-filters.php
Replace the standard WP "author" link with a link to the BuddyPress user domain.
> Filter the link returned in the WP API users response.

- includes/bp-activity/classes/class-bp-rest-activity-endpoint.php
- tests/activity/test-controller.php
- tests/members/test-controller.php
I will play around with the BP Rest API. So here's my first contribution :)
Unittest fix + fixes the fact `BP_REST_Activity_Endpoint->delete_item_permissions_check()` is too permissive as any logged in user could delete any activity item.
> Fix Activity delete permission failing unittest

- includes/bp-activity/classes/class-bp-rest-activity-endpoint.php
- includes/bp-notifications/classes/class-bp-rest-notifications-endpoint.php
- tests/activity/test-controller.php
This method is used in the get_items() one to know if hide_sitewide activities should be fetched for the loggedin user.
1. As the default value of the primary id is an array, in order to avoid errors when checking if the user is a member/admin/mod of the group we need to extract the first value of this array.
2. Public Groups activities should be fetchable for any logged in user
3. A filter makes it possible for custom components to add their own logic about the hide_sitewide param.
4. If statements have been reorganized to avoid unnecessary checks.
5. bp_loggedin_user_id() does not seem to be set during a REST API request, get_current_user_id() is.
> Improve the BP_REST_Activity_Endpoint->show_hidden() method

- includes/bp-members/classes/class-bp-rest-members-endpoint.php
- tests/members/test-controller.php
The BP_REST_Members_Endpoint class extends the WP_REST_Users_Controller one but has a different item schema. In particular, it uses an unrequired user_login key where the parent is using a required username key. As a result creating an item is generating a PHP error in the wp_insert_user() function at line 1526.
The fix is making the user_login key required, and extends the prepare_item_for_database() method so that the user_login is successfully prepared.
> The user_login is a required field to insert a new user.

- includes/bp-activity/classes/class-bp-rest-activity-endpoint.php
- includes/bp-members/classes/class-bp-rest-members-endpoint.php
- tests/activity/test-controller.php
Using the method as a plugin is quite complex as it requires to filter bp_activity_add() making sure a rest request is being performed. I suggest to be nicer with plugins wishing to use the BP Rest API and in particular this activity endpoint by:
Allowing custom components to create items, for instance I see no reason to restrict Activity creation to Core components, it should be available for all active components.
It should allow hidden activities to be created, the Group will need it anywayfor the ! public statuses.
This PR also improves some parts like:
- use a default value for the user ID as bp_loggedin_user_id() is not set in activity functions when creating Group Activities (get_current_user_id() is now used as the default value)
- add the missing unit tests for the create item …
> Make BP_REST_Activity_Endpoint->create_item() more friendly to BP plugins

- bp-rest.php
- includes/bp-activity/classes/class-bp-rest-activity-endpoint.php
- includes/functions.php
- tests/activity/test-controller.php
Client scripts need to be informed about the total amount of activities found for the request and about the total amount of available pages for the results of the request. Otherwise building a pagination is not possible and it needs the script to keep on requesting untill the response returns no results.
To avoid altering the response data with these two piece of informations, I suggest to use the allowed headers made available by the WordPress REST API :
- X-WP-Total is informing about the total amount of activities found.
- X-WP-TotalPages is informing about the number of pages.
> Add Response headers about total number of activities and pages

- includes/bp-activity/classes/class-bp-rest-activity-endpoint.php
- phpunit.xml.dist
- tests/activity/test-controller.php
Instead of having the raw data fetched into the view context, I think we should provide rendered activities into this context and provide both (raw data + rendered activity) into the edit context.
In other words, we need to make sure the activity content filters are fired to sanitize the output/run formatting filters when the context is a view one.
I suggest to do just like WordPress does for the Post Types : using an object type for the content key of the schema with raw and rendered properties.
From the client side, developers will need to update their scripts to display the content and use data.content.rendered instead of data.content for instance.
FYI I've added a test about embeds into activity content, to avoid a fatal error now WordPress is using a build/src architecture I've …
> Activities need to be rendered

- README.md
- includes/bp-activity/classes/class-bp-rest-activity-endpoint.php
- tests/activity/test-controller.php
The idea is to implement it a bit differently than how it is done in AJAX. The user is updating their favorites for a specific activity Rest request.
When fetching activities so that it is easy for a client to know whether an activity is favorited or not, i have updated the schema with a readonly property (favorited).
I am only getting the user favorites for get_items/get_item and update_favorite methods as i dont think we need it elsewhere
> Add Activity favorites

- includes/bp-groups/classes/class-bp-rest-groups-endpoint.php
It was changed in https://buddypress.trac.wordpress.org/changeset/11090.
@renatonascalves Submitted for your perusal :-D
> Don't use old function signature for `groups_get_group()`.

- includes/bp-activity/classes/class-bp-rest-activity-endpoint.php
- tests/activity/test-controller.php
Currently, if you have an activity item tied to a public group, it's not possible to query for that item unless you're a member of that group. This incorrect behavior is caused by https://github.com/buddypress/BP-REST/blob/b639328eb5ad319b60c30951f7ef1b644a8ff25d/includes/bp-activity/classes/class-bp-rest-activity-endpoint.php#L217
There are two problems with the check here. One is that it doesn't cover the case of public groups. The other is that it's redundant: `get_item_permissions_check()` happens before, and calls `can_see()`; this, in turn, calls `bp_activity_can_read()`, which does a (more thorough) group membership check. I've included a test that verifies this.
> Activity show hidden

- includes/bp-members/bp-members-filters.php
The `bp_remove_has_published_posts_from_wp_api_user_query()` filter affects *all* API queries. This feels like unexpected behavior to me. IMO we should be more conservative here, only modifying the query if we know it's the BP `/members/` query.
First question is whether you agree with me about this. I don't have a really great argument :-D But, if I were building an external client that fetched a list of users at `/users/`, I'd expect to be able to use the `has_published_posts` param whether or not BP was involved.
Second question is how to implement. In this PR I specified the `/members/` endpoint, but if we extend the core `users` query elsewhere in BP-REST, then we might want to make it more general. The hardcoding of the namespace, version number, and `rest_base` also seem wrong to …
> Don't modify core /users/ query results.

- includes/bp-groups/classes/class-bp-rest-group-members-endpoint.php
- tests/groups/test-group-member-controller.php
I began a review of #126 and, as in the case of the group membership endpoint, I found myself unhappy with the semantics of the URI format. `/group/invites/123`, where 123 is the user ID, doesn't make much sense to me.
So I thought I'd suggest a different format. Instead of applying it to the WIP invites endpoint, I've applied it to the already-merged members endpoint. Here's the new format:
`GET /groups/<group-id>/members`
`PUT (or POST) /groups/<group-id>/members/<user-id>`
`DELETE /groups/<group-id>/members/<user-id>`
This feels much more semantic, and I think we can apply a similar pattern elsewhere in the endpoints (such as for group invites). @renatonascalves Can you please give me your opinion on whether this is an improvement over what's currently there?
> Updated URI format for group member endpoint.

- includes/bp-members/classes/class-bp-rest-members-endpoint.php
The members endpoint, when using `bp_xprofile_get_groups()`, should check if the `xprofile` component is active first. Otherwise it will generate a fatal error if the xProfile component is not active.
> Make sure xProfile component is active before using it

- bp-rest.php
When building endpoint for a JavaScript use, we need to be able to use:
- `bp_rest_namespace()`
- `bp_rest_version()`
Another option could be to simply move them into the `bp-rest.php` file.
> Make sure generic functions are available outside of a REST request

- includes/bp-activity/classes/class-bp-rest-activity-endpoint.php
- includes/bp-groups/classes/class-bp-rest-group-membership-endpoint.php
- includes/bp-groups/classes/class-bp-rest-groups-endpoint.php
- includes/bp-members/classes/class-bp-rest-members-endpoint.php
- includes/bp-xprofile/classes/class-bp-rest-xprofile-field-groups-endpoint.php
- includes/bp-xprofile/classes/class-bp-rest-xprofile-fields-endpoint.php
- tests/membership/test-group-membership-controller.php
The `rest_validate_request_arg()` function is checking for the type of the values an array contains. When omitting to set it for array types parameters it generates a notice error. A unit test about requesting group mods is also included as it is the way I found the notice error.
FYI @renatonascalves that's what I was talking about into the [8045 ticket on trac](https://buddypress.trac.wordpress.org/ticket/8045#comment:13).
> Make sure the items proprerty is defined when the parameter type is an array

- includes/bp-activity/classes/class-bp-rest-activity-endpoint.php
`bp_is_active( $component )` when `$component` is `NULL` is `true` as a result the groups functions used into the `show_hidden()` method of the Activity REST endpoint are unknown.
Using the `is_null()` check fixes this issue.
> Prevent a fatal error when the groups component is inactive

- includes/bp-activity/classes/class-bp-rest-activity-endpoint.php
I just found a situation where a fatal error happened when BP_REST_Activity_Endpoint->prepare_links() is run: On a multisite config where BuddyPress is activated on two subsites. The first site has the groups component active the other one has not. As all activities no matter from what site they were posted are displayed in every site, I think it is safer to always check a component is active before using one of its function within the Activity Endpoint.
> Check the group is active before using one of the component function

- bp-rest.php
This makes sure BP REST endpoints are loaded if BuddyPress is active. Using a function name to wrap the code is also very interesting as it allowes us to keep all options about the core merging/including strategy. For instance:
- we can avoid loading REST endpoints into BuddyPress if `has_action( "bp_rest_init_api_init", "bp_rest", 5 )`
- or we can disable the BP REST plugin endpoints from BuddyPress using `remove_action( "bp_rest_api_init", "bp_rest", 5 )`
Fixes #185
PS : I’ve tested it with https://buddypress.trac.wordpress.org/ticket/8045 + unitests 👌
> Use the `bp_rest_api_init` hook to register the REST controllers

- includes/bp-groups/classes/class-bp-rest-group-membership-request-endpoint.php
The extra tab at the beginning of `class-bp-rest-group-membership-request-endpoint.php` can break the headers of the WP Rest Server as there are then "already sent".
> Fix failing headers of the WP Rest Server

- bp-rest.php
I think the only thing we need to do is to make sure to avoid a fatal error when BuddyPress will contain the functions of the`includes/functions.php` file.
> Prepare BuddyPress core inclusion

- includes/bp-messages/classes/class-bp-rest-messages-endpoint.php
- tests/messages/test-controller.php
I think we shouldn't try to manage Site Wide notices into the Messages endpoint. It should have its own endpoint.
- Add a specific REST route to toggle whether a message is starred or not.
- Add corresponding unit tests.
This new method makes it easier to prepare each message of the Thread and in particular point **4** 👇.
- Fixes #190 
- Add the `BP_REST_Messages_Endpoint::update_item()` & corresponding check method to allow REST Additional fields update only: the message or the reply remains unchanged.
- Make `BP_REST_Messages_Endpoint::prepare_item_for_response()` more consistent with item schema
- Bring replies support to the `BP_REST_Messages_Endpoint::create_item()` method
> Improve the Messages Endpoint

- includes/bp-members/classes/class-bp-rest-members-endpoint.php
For the members endpoint, we do not need all the `WP_REST_Users_Controller::get_collection_params()`. We only need the context, page, per_page and search. (who, roles, offset etc.. are not used by `BP_User_Query`).
> Make sure the collection params are consistent with BP_User_Query

- includes/bp-activity/classes/class-bp-rest-activity-endpoint.php
- tests/activity/test-controller.php
1. Make sure the `id` is listed as an argument for the `buddypress/v1/activity/<id>` and `buddypress/v1/activity/<id>/favorite` routes
2. Set the type of the content argument to `string` for CREATABLE and EDITABLE transport methods.
3. Set the type argument as required for the EDITABLE method (adapt the unit tests accordingly).
4. Improve strings used to describe the argument replacing "objetc" by "activity".
5. Set the status, comments, comment_count arguments as read only to remove them from EDITABLE and CREATABLE transport methods.
6. Set the title as readonly: activity actions are generated dynamically and remove the readonly property from the link argument: link is editable.
Note about the status: we will probably need specific routes to an spam/ham activity in a future release.
The …
> Improve arguments description for the Activity endpoint methods

- includes/bp-xprofile/classes/class-bp-rest-xprofile-field-groups-endpoint.php
- includes/bp-xprofile/classes/class-bp-rest-xprofile-fields-endpoint.php
- tests/xprofile/test-field-controller.php
1. Remove the duplicate `hide_empty_groups` parameter from the Group and Profile field endpoints.
2. Remove the `create_update_item_params()` method in favor of `get_endpoint_args_for_item_schema()` for consistency with other endpoints.
3. Make sure the ID is listed in arguments for the `/buddypress/v1/xprofile/fields/<id>` routes.
4. Set the default property of the `user_id` to `0` to avoid requesting for profile data by default for the GET transport method of `/buddypress/v1/xprofile/fields/<id>` route.
5. Introduce `get_endpoint_args_for_item_schema()` to build the schema for the EDITABLE and CREATABLE transport methods.
5.1 Make sure the visibility and autoling property of fields can be set using the endpoint.
5.2 Make sure `group_id`, `type`, and `name` are described as Required for …
> Improve Profile field arguments and some xProfile field features

- includes/bp-members/classes/class-bp-rest-members-endpoint.php
- includes/bp-xprofile/classes/class-bp-rest-xprofile-data-endpoint.php
- includes/bp-xprofile/classes/class-bp-rest-xprofile-fields-endpoint.php
- tests/xprofile/test-data-controller.php
To preserve some consistency about data types and to make sure values are fully usable I have first edited the way field values are populating the REST responses (possibly into the Member, Profile Group, Profile Field and Profile Data endpoints):
- the `value` property is now an object exposing 3 versions of the value:
- `raw` is the db version of the value (edit context only),
- `unserialized` is always an array containing one or more field values (for instance checkboxes or multi-selectbox),
- `rendered` is the HTML string output on the front-end. It may contain a link if the field has an `autolink` status set to `on`.
- an array is expected when saving a profile data. This is to take in account checkboxes or multi-selectbox which accept multiple values. If a string is used, it is …
> Improve Profile data arguments and the way are retrieved field values

- includes/bp-groups/classes/class-bp-rest-groups-endpoint.php
- tests/groups/test-controller.php
1. Make sure the ID argument is listed into the `buddypress/v1/groups/<group_id>` routes.
2. Edit some arguments specifically for the EDITABLE and CREATABLE methods:
- Set the group description type to `string` for both methods
- Remove the slug argument from the available arguments for the EDITABLE one.
3. The `user_id` was not an argument, I have changed it for the existing `creator_id`
4. In the `prepare_item_for_database()` method: If the `creator_id` is not set, we need to fallback on the existing `creator_id` if set (Group update) otherwise the current user (Group create).
5. The `slug` needs more checks: if it is a group creation we fall back on the group `name` if the `slug` hasn't been sent into the request. If it is an update and the `slug` is not the same than the existing one …
> Improve Groups endpoint arguments and fix potential issues

- includes/bp-groups/classes/class-bp-rest-group-membership-endpoint.php
- includes/bp-members/classes/class-bp-rest-members-endpoint.php
- tests/membership/test-group-membership-controller.php
1. Use `groups_join_group()` into the `view` context of `BP_REST_Group_Membership_Endpoint->create_item()`. The existing code to add a user to a group has been restricted to site administrators.
2. Adapt unit tests and add one to test the `edit` context for Administrators.
3. Make sure the user trying to join a public group is not already a member and has not been banned from the group.
4. Improve `BP_REST_Members_Endpoint->user_data()` to accept a context argument so that using the edit context will retrieve caps, roles etc..
5. Add an [Info block to the documentation](https://imath-buddydocs.pf1.wpserveur.net/bp-rest-api/reference/user-groups/group-membership/#add-a-specific-member-into-a-group) of the route to inform how to make a logged in user join a public group.
NB: this PR is …
> Use the view context to let regular users join a public group

- includes/bp-activity/classes/class-bp-rest-activity-endpoint.php
- includes/bp-groups/classes/class-bp-rest-group-membership-endpoint.php
- includes/bp-groups/classes/class-bp-rest-groups-endpoint.php
- includes/bp-messages/classes/class-bp-rest-messages-endpoint.php
- includes/bp-notifications/classes/class-bp-rest-notifications-endpoint.php
- includes/bp-xprofile/classes/class-bp-rest-xprofile-data-endpoint.php
- includes/bp-xprofile/classes/class-bp-rest-xprofile-field-groups-endpoint.php
- includes/bp-xprofile/classes/class-bp-rest-xprofile-fields-endpoint.php
- tests/activity/test-controller.php
- tests/groups/test-controller.php
- tests/membership/test-group-membership-controller.php
- tests/notifications/test-controller.php
- tests/xprofile/test-data-controller.php
- tests/xprofile/test-field-controller.php
- tests/xprofile/test-group-controller.php
As discussed during August 7th dev chat, I think it's important we harmonize how we build the responses of the endpoints `delete_item()` methods.
I've suggested to do just like the WP REST API does for this case. One good reason to do so is: our Members endpoint extends the WP Users one and already uses this specific way to build responses. See the extract of `WP_REST_Users_Controller->delete_item()` code below:
```php
$result = wp_delete_user( $id, $reassign );
if ( ! $result ) {
return new WP_Error( 'rest_cannot_delete', __( 'The user cannot be deleted.' ), array( 'status' => 500 ) );
}
$response = new WP_REST_Response();
$response->set_data(
array(
'deleted'  => true,
'previous' => $previous->get_data(),
)
);
```
This PR is applying this to all endpoints except for the 2 ones @dcavins …
> Harmonize delete_item() method responses

- includes/bp-messages/classes/class-bp-rest-messages-endpoint.php
- tests/messages/test-controller.php
1. Edit the item schema to be able to use it for CREATABLE/EDITABLE/DELETABLE transport methods.
2. Use `BP_REST_Messages_Endpoint->get_endpoint_args_for_item_schema()` to adjust arguments properties.
3. Remove `BP_REST_Messages_Endpoint->prepare_item_for_database()`: as `BP_REST_Messages_Endpoint->update_item()` is only editing metadata, it was only used by the `create_item()` method.
4. Simplify how the arguments for `messages_new_message()` are generated in the `create_item()` method.
5. Adapt Messages Unit tests accordingly.
The [Messages Endpoints documentation](https://imath-buddydocs.pf1.wpserveur.net/bp-rest-api/reference/private-messaging/) has been written taking these changes in account.
> Improve Messages endpoint arguments

- includes/bp-groups/classes/class-bp-rest-group-membership-endpoint.php
Just fixes the parameter order for groups_join_group(). No unit tests sorry.
> fix: users incorrectly joined to groups

- bp-rest.php
- includes/bp-groups/classes/class-bp-rest-group-invites-endpoint.php
- includes/bp-groups/classes/class-bp-rest-group-membership-request-endpoint.php
- tests/groups/test-group-invites-controller.php
- tests/membership/test-group-membership-request-controller.php
Here's an updated PR with changes to the group membership requests and invitations endpoints.
> Group membership requests and invitations update.

- includes/bp-groups/classes/class-bp-rest-group-membership-endpoint.php
- tests/membership/test-group-membership-controller.php
The route to create a new membership should be consistent with what we do in all other endpoints. Thats is to say: do not pass the user ID as the last part of the route. In other words: instead of using `/buddypress/v1/groups/<group_id>/members/<user_id>` we should be using `/buddypress/v1/groups/<group_id>/members` and pass the `user_id` into the request arguments.
This PR brings this improvement. It also adapts the unit tests.
_NB: on a site note, the REST Server used into the unit tests is not setting the current user at the time it fetches the routes arguments. This means, unlike what happens on the regular WP REST SERVER, the default value set to `bp_loggedin_user_id()` is `0` althought the current user is defined. That is why I added the `user_id` request argument on all …
> Improve the Group Membership Controller

- includes/bp-groups/classes/class-bp-rest-group-invites-endpoint.php
- includes/bp-groups/classes/class-bp-rest-group-membership-request-endpoint.php
- tests/groups/test-group-invites-controller.php
- tests/membership/test-group-membership-request-controller.php
Improve the response to `delete` requests by adding a `deleted` boolean and putting the now-deleted invite data into `previous`, similar to the pattern used elsewhere in the REST API.
> Improve group invites/requests DELETE response.

- includes/bp-groups/classes/class-bp-rest-group-membership-request-endpoint.php
- tests/membership/test-group-membership-request-controller.php
- Improve the item schema and collection params
- fix a remaining PHPCS issue
- Make sure the current user is reset before every Group Membership requests unit tests.
The [documentation](https://imath-buddydocs.pf1.wpserveur.net/bp-rest-api/reference/user-groups/group-membership-requests/) for the Group Membership Requests endpoints has been written taking these points in account.
> Improve the Groups Membership requests item schema & collection arguments

- includes/bp-attachments/classes/class-bp-rest-attachments-member-avatar-endpoint.php
- includes/bp-attachments/classes/trait-attachments.php
- tests/attachments/test-member-avatar-controller.php
- Make sure the get_item response is consistent with the item schema. That is to say: always return the full and thumb version of the avatar.
- Add the `action` argument to the CREATABLE transport method: `BP_REST_Attachments` should not override the $_POST global.
- Add a unit test for the `create_item` method
- Fix the wrong use of sprintf in `BP_REST_Attachments->upload_avatar_from_file()`
- Introduce `BP_REST_Attachments->get_avatar_object()` to build the avatar object
Write the [documentation](https://imath-buddydocs.pf1.wpserveur.net/bp-rest-api/reference/attachments/member-avatar/) about this controller taking in account these changes.
> Improve the Member Avatar Endpoint

- includes/bp-attachments/classes/class-bp-rest-attachments-group-avatar-endpoint.php
- tests/attachments/test-group-avatar-controller.php
- Make sure the get_item response is consistent with the item schema. That is to say: always return the full and thumb version of the avatar.
- Add the `action` argument to the CREATABLE transport method.
- Add a unit test for the `create_item` method.
Write the [documentation](https://imath-buddydocs.pf1.wpserveur.net/bp-rest-api/reference/attachments/group-avatar/) about this controller taking in account these changes.
> Improve the Group Avatar Controller

- includes/bp-groups/classes/class-bp-rest-group-membership-endpoint.php
The membership actions are not translated as a result, the error message cannot be fully translated.
> Translation strings shouldn't use a placeholder for an untranslated string

- includes/bp-groups/classes/class-bp-rest-group-membership-endpoint.php
In the Group Membership controller: returning an error when a user cannot perform an action needs to include the actions into the translated strings.
Using a placeholder here will leave the `demote`, `ban` & `unban` terms unstranslated.
> Actions shouldn't be used in translation placeholders II

- includes/bp-activity/classes/class-bp-rest-activity-endpoint.php
- includes/bp-attachments/classes/class-bp-rest-attachments-group-avatar-endpoint.php
- includes/bp-attachments/classes/class-bp-rest-attachments-member-avatar-endpoint.php
- includes/bp-attachments/classes/trait-attachments.php
- includes/bp-groups/classes/class-bp-rest-group-invites-endpoint.php
- includes/bp-groups/classes/class-bp-rest-group-membership-endpoint.php
- includes/bp-groups/classes/class-bp-rest-group-membership-request-endpoint.php
- includes/bp-groups/classes/class-bp-rest-groups-endpoint.php
- includes/bp-members/classes/class-bp-rest-members-endpoint.php
- includes/bp-messages/classes/class-bp-rest-messages-endpoint.php
- includes/bp-notifications/classes/class-bp-rest-notifications-endpoint.php
- includes/bp-xprofile/classes/class-bp-rest-xprofile-data-endpoint.php
- includes/bp-xprofile/classes/class-bp-rest-xprofile-field-groups-endpoint.php
- includes/bp-xprofile/classes/class-bp-rest-xprofile-fields-endpoint.php
1. There was 2 missing text domains (`buddypress`).
2. `id` or `ID`.. I chose `ID` everywhere :)
3. I also tried to limit ways of writing the same thing. Eg: not authorized ~ unauthorized or sometimes a full stop was missing.
4. I fixed a misuse of the %1$s placeholder
5. I fixed a translator comment where %$1s was used instead of %s
> Fix some i18n issues

- bp-rest.php
- includes/bp-signup/classes/class-bp-rest-signup-endpoint.php
- tests/signup/test-controller.php
> Signup Endpoints

- README.md
- bp-rest.php
- includes/bp-friends/classes/class-bp-rest-friends-endpoint.php
- includes/bp-groups/classes/class-bp-rest-group-invites-endpoint.php
- includes/bp-signup/classes/class-bp-rest-signup-endpoint.php
- tests/friends/test-controller.php
> Friends Endpoints

- bp-rest.php
As discussed during October 30 dev-chat: until the Member Avatar dependency to xProfile is removed in BuddyPress Core, we will make sure to load the Member Avatar Controller only if the xProfile component is active.
Documentation about this fact has been updated, see [Member Avatar chapter](https://developer.buddypress.org/bp-rest-api/reference/attachments/member-avatar/).
Fixes #249
> Load the Member Avatar Controller if the xProfile component is active

- includes/bp-groups/classes/class-bp-rest-groups-endpoint.php
- tests/groups/test-controller.php
1) Regular users should not be able to use the `edit` context.
2) Some user data should be unset like the user_pass or the user_email when building the list of mods/admins/members inside the `edit` context.
**Important**:  we'll need to backport the fix on [branch 0.1](https://github.com/buddypress/BP-REST/tree/0.1)
> Fix 2 issues about the `edit` context for the Groups controller get_items() method

- includes/bp-friends/classes/class-bp-rest-friends-endpoint.php
The update_item endpoint query schema contains unused arguments, this removes them.
> Removes unsed query args from friends update_item endpoint

- includes/bp-activity/classes/class-bp-rest-activity-endpoint.php
- includes/bp-attachments/classes/trait-attachments.php
- includes/bp-blogs/classes/class-bp-rest-blogs-endpoint.php
- includes/bp-groups/classes/class-bp-rest-groups-endpoint.php
- includes/bp-members/classes/class-bp-rest-members-endpoint.php
Now we are using WP CLI to generate the BuddyPress pot file, we need to have consistent translators comments for i18n strings. The comment changes are making sure we are using the same in BuddyPress or into the BP REST API considering the same strings. It also fixes WP CLI warnings when releasing BuddyPress.
See [#8260](https://buddypress.trac.wordpress.org/ticket/8260) for more info.
> Improve translators comments

- tests/attachments/test-blog-avatar-controller.php
- tests/blogs/test-controller.php
BuddyPress trunk is no more using 5.1 deprecated hooks for the Blogs component. We do not need anymore to expect some deprecation into BP REST unit tests.
> Update Blogs component unit test to BP Trunk latest changes

- includes/bp-activity/classes/class-bp-rest-activity-endpoint.php
- includes/bp-messages/classes/class-bp-rest-messages-endpoint.php
Since [WP47559](https://core.trac.wordpress.org/changeset/47559/) forcing this parameter generates failing tests.
I do not think we need to do this.
Could you have a look at it @renatonascalves ?
> Stop forcing the context parameter of the request

- includes/bp-groups/classes/class-bp-rest-group-membership-endpoint.php
#299 is fixing the failing tests here.
I've checked, `groups_remove_member()` returns false if `!  bp_is_item_admin()`. `bp_is_item_admin()` is not containing mods but only admins, see [src/bp-groups/classes/class-bp-groups-component.php#L311](https://github.com/buddypress/BuddyPress/blob/master/src/bp-groups/classes/class-bp-groups-component.php#L311)
> Make sure only the Group Admin can delete others membership

- includes/bp-members/classes/class-bp-rest-signup-endpoint.php
- tests/signup/test-controller.php
While I was working on #301 I've found this issue.
`per_page` is not the offset, it is the `number`. To avoid confusions I think we should use `number` & `offset` parameters  for signups.
Let's fix it before 6.0.0-RC1 [April 29](https://wordpress.slack.com/archives/C02RQBYUG/p1587584053231800) ;)
> Make sure to use the right number/offset collection params for signups

- includes/bp-members/classes/class-bp-rest-signup-endpoint.php
- tests/signup/test-controller.php
I'm still working on the documentation of this endpoint and I believe we should improve it in various areas:
1. We should provide the available `orderby` options, that's why I've created [this ticket upstream](https://buddypress.trac.wordpress.org/ticket/8284)
2. The `user_name` argument is only available if the xProfile component is active and in this case it is required.
3. We need to save the signup meta during the create_item method. It must contain at least the user `password` and the `user_name`.
4. I'm including new properties to the schema such as `meta`, `date_sent` and `count_sent` for the edit context as I believe these are important ones.
Thanks for your review about it, and let's try to fix this before this wednesday.
> Improve the Signup endpoint

- includes/bp-blogs/classes/class-bp-rest-attachments-blog-avatar-endpoint.php
- includes/bp-blogs/classes/class-bp-rest-blogs-endpoint.php
- tests/blogs/test-controller.php
1. The `BP_REST_Blogs_Endpoint` controller was never fetching avatars because the condition to add the `avatar_urls` property to the schema is the opposite of what it should be. Instead of `! buddypress()->avatar->show_avatars` it musts be `buddypress()->avatar->show_avatars`.
2. I've improved the `BP_REST_Attachments_Blog_Avatar_Endpoint` controller so that:
- There is no need anymore to include a `user_id` argument to get the fallback admin avatar. It seemed weird to me it was more difficult to get the blog avatar from this controller than from the `BP_REST_Blogs_Endpoint` one. To do so I'm simply "catching" the Blog object during the permission check to avoid requerying.
- I've added the `html` property to the collection params to improve consistency with the other avatar endpoints. I …
> Improve blog avatar into the Blogs endpoints

- includes/bp-members/classes/class-bp-rest-attachments-member-avatar-endpoint.php
As the `get_item()` method is using `$request['no_gravatar']` to set the `no_grav` argument of the function to fetch the user avatar, the collection param must be `no_gravatar` so that it is taken in account during GET requests.
I've updated the documentation page: https://developer.buddypress.org/bp-rest-api/reference/attachments/member-avatar/
> Member Avatar: Rename the `no_grav` to `no_gravatar`

- includes/bp-attachments/classes/trait-attachments.php
- includes/bp-members/classes/class-bp-rest-attachments-member-cover-endpoint.php
- Make sure the cover image is fetched once uploaded. So far it's an empty image.
- Make sure the Groups component is the current one when uploading a Group Cover image otherwise the file is uploaded into the current members's cover image directory.
The documentation for these endpoints has been created, see #301
> Group and Members Cover image

- includes/bp-groups/classes/class-bp-rest-group-membership-endpoint.php
- tests/membership/test-group-membership-controller.php
See https://buddypress.trac.wordpress.org/ticket/8299
In short using `NULL` as the default value can generate SQL overheat unnecessarily.
BTW we should probably create a 0.2 branch in case some new features need to be added to the plugin.
This way this 0.2 branch would be used by the BuddyPress 6.0 branch.
> Group Membership Endpoint: search_terms should default to false

- bp-rest.php
- package-lock.json
- package.json
I’ve just created [branch 0.2](https://github.com/buddypress/BP-REST/tree/0.2). It corresponds to the BuddyPress 6.0 branch (see [12658](https://buddypress.trac.wordpress.org/changeset/12658)). To work on new features, I think it is safer to bump plugin version to 0.3.0
> Bump plugin version to 0.3.0

- includes/bp-groups/classes/class-bp-rest-groups-endpoint.php
- tests/groups/test-controller.php
In order to easily fetch current user’s groups in JavaScript, it would be very convenient to add this route. I believe, it might also be interesting for some other components (friends, blogs..).
This groups route is really important when checking if a user can post activities to groups for instance. (currently working on using the BP REST API to post activities 😉 )
> Add a groups/me route to get current users’s group

- includes/bp-groups/classes/class-bp-rest-groups-endpoint.php
- tests/groups/test-controller.php
The information from the `buddypress/v1/groups/group_id` endpoint is already available in the `get_items` endpoint from this component. So there is no need to hide it from public view.
Also, with this change, a few unit tests became redudant, so they were removed.
closes #314
> Allow Group details to be available in its single endpoint

- includes/bp-activity/classes/class-bp-rest-activity-endpoint.php
- tests/activity/test-controller.php
When posting an activity into a private or hidden group, the response does not include the posted activity because in this case `$request['hidden']` is not set.
Using `true` for the `show_hidden` argument used into `bp_activity_get` seems fine as anyway the activity has been created by the user, I don't see any reason preventing him to be able to read it 😃 
I've added some tests for the `create_item` method and one for the `update_item` method to make sure this issue wasn't also appearing when updating an activity of a non public group.
> Make sure the response of activity posted in a group is the activity

- includes/bp-groups/classes/class-bp-rest-groups-endpoint.php
I'm suggesting a change in how we check for the permissions when trying to list groups. Right now, if a person tries to list hidden groups but have no permission to do so, we return an error object. That seems too much.
I'm suggesting we don't show an error object but instead return the public and private groups. Users with permissions to see the groups, will continue to do so if they choose it, of course.
> List hidden groups if user has permissions, otherwise return public and private groups

- includes/bp-activity/classes/class-bp-rest-activity-endpoint.php
- includes/bp-attachments/classes/trait-attachments.php
- includes/bp-blogs/classes/class-bp-rest-blogs-endpoint.php
- includes/bp-components/classes/class-bp-rest-components-endpoint.php
- includes/bp-friends/classes/class-bp-rest-friends-endpoint.php
- includes/bp-groups/classes/class-bp-rest-group-invites-endpoint.php
- includes/bp-groups/classes/class-bp-rest-group-membership-request-endpoint.php
- includes/bp-groups/classes/class-bp-rest-groups-endpoint.php
- includes/bp-notifications/classes/class-bp-rest-notifications-endpoint.php
- includes/bp-xprofile/classes/class-bp-rest-xprofile-field-groups-endpoint.php
- tests/activity/test-controller.php
- tests/attachments/test-blog-avatar-controller.php
- tests/components/test-controller.php
- tests/friends/test-controller.php
- tests/groups/test-controller.php
- tests/groups/test-group-invites-controller.php
- tests/membership/test-group-membership-request-controller.php
Hey team :hand:,
We should return `4xx` error code instead of `500` for bad requests like `empty_content`, `invalid_id` etc.  A `500` error code is for internal server errors.
I updated some of them and I'll keep update but I'm open to help and any suggestions.
> Update wrong HTTP status codes

- .travis.yml
- README.md
- bp-rest.php
- readme.txt
As BuddyPress core is raising its support to WordPress 4.9: https://buddypress.trac.wordpress.org/ticket/8318 The REST API is following suit. :)
> Raising WordPress required version to 4.9

- includes/bp-groups/classes/class-bp-rest-groups-endpoint.php
- includes/bp-xprofile/classes/class-bp-rest-xprofile-data-endpoint.php
fixes #324 
I'm suggesting an update at how we parse the strings when updating a profile field. Currently the value that's being passed goes to `wp_parse_list` which is splitting the array/value incorrectly.
A list like so: `Select 01, Select 02` will be converted as `["Select","01","Select","02"]` instead of `["Select 01","Select 02"]`. The main issue is the regex used: `/[\s,]+/` which takes into account spacing when splitting the array, causing the bug.
So to avoid this bug, I opted to pass the value as a string and split it accordingly before the profile field update. First, we check if the field `supports_multiple_defaults`, if it doesn't, we pass it as a string. If it does, we split it as it accepts an array with multiple values.
This is a breaking change, though. Since we are …
> Profile Data Update

- includes/bp-activity/classes/class-bp-rest-activity-endpoint.php
- tests/activity/test-controller.php
fixes #353 
With this change, one can fetch activities from a group (private or not) in two ways:
`wp-json/buddypress/v1/activity?primary_id=1&component=custom`
`wp-json/buddypress/v1/activity?group_id=1`
> Improving fetching of activities from private groups

- includes/bp-members/classes/class-bp-rest-members-endpoint.php
- tests/members/test-controller.php
To set the current user's last activity into `BP_REST_Members_Endpoint::user_data()` we should use the current time.
> Improve the way the last activity is set for the current user

- includes/bp-blogs/classes/class-bp-rest-attachments-blog-avatar-endpoint.php
- tests/attachments/test-blog-avatar-controller.php
If the `no_user_grav` param is set to true, then the blavatar fetched will be the default one.
Add unit tests to check the 3 available scenario when fetching the blog avatar:
- site icon is used
- no user gravatar is requested
- use the admin user avatar
See: https://buddypress.trac.wordpress.org/changeset/12772
> Take in account BP 7.0.0 changes about default blavatar

- includes/bp-members/classes/class-bp-rest-members-endpoint.php
- tests/members/test-controller.php
Working on documentation updates, I noticed the `types` parameter of the documentation wasn't used by create/update methods. Instead we were using a `member_type` parameter that wasn't sanitized. This was probably due to the fact until BuddyPress 7.0.0 it wasn't possible to assign more than one member type to a member. As `bp_rest_sanitize_member_types()` is returning an array, it was causing an error in BuddyPress.
In BuddyPress 7.0.0, it's now possible to set multiple member types to a member. That's why I edited the schema for create/update methods so that it actually uses the `member_type` parameter and in case some people are using the `types` one it will be used to set the `member_type` parameter into the `BP_REST_Members_Endpoint->prepare_item_for_database()` method.
I've added 2 …
> Do assign member types into the Members Endpoint

- includes/bp-members/classes/class-bp-rest-members-endpoint.php
These are small fixes to make sure schemas are consistent. The Members Endpoint documentation has been updated accordingly, see https://developer.buddypress.org/bp-rest-api/reference/members/
> Improve Members endpoints schemas

- includes/bp-members/classes/class-bp-rest-members-endpoint.php
- tests/groups/test-controller.php
- tests/members/test-controller.php
The `members_type` property of the item schema should be an array instead of an object. I've updated this property in a similar way then what we're doing for the Groups endpoints types item schema property. I've also added unit tests for both endpoints.
> Improve the member_types property of the members endpoint item schema

- includes/bp-groups/classes/class-bp-rest-groups-endpoint.php
- includes/bp-xprofile/classes/class-bp-rest-xprofile-data-endpoint.php
The sanitize function for Group Types `bp_rest_sanitize_group_types()` requires data to be a string, if it's an array it generates an error.
I've updated the documentation accordingly.
> Improve Groups and xProfile endpoints item schema

- tests/attachments/test-blog-avatar-controller.php
We can now directly use `bp_blogs_default_avatar()` see https://buddypress.trac.wordpress.org/changeset/12772
> Adapt a Blogs Endpoint unit test to latest BP changes

- includes/bp-members/classes/class-bp-rest-members-endpoint.php
- includes/bp-xprofile/classes/class-bp-rest-xprofile-fields-endpoint.php
- tests/attachments/test-group-avatar-controller.php
- tests/attachments/test-member-avatar-controller.php
PHP 8.0 no longer accepts a required argument to follow an optional one into functions.
> Avoid a PHP 8.0 deprecated notice about optional function arg.

- .travis.yml
- bp-rest.php
- package.json
- phpcs.xml.dist
- phpunit.xml.dist
- readme.txt
From now on we need to use `@since 8.0.0` for new introduced functions/classes as this will be included into BuddyPress 8.0.0. FYI, the 0.3 branch has been created for the BuddyPress 7.0 branch
> 0.4.0 version bumps

- includes/bp-activity/classes/class-bp-rest-activity-endpoint.php
- includes/bp-blogs/classes/class-bp-rest-attachments-blog-avatar-endpoint.php
- includes/bp-blogs/classes/class-bp-rest-blogs-endpoint.php
- includes/bp-components/classes/class-bp-rest-components-endpoint.php
- includes/bp-friends/classes/class-bp-rest-friends-endpoint.php
- includes/bp-groups/classes/class-bp-rest-attachments-group-avatar-endpoint.php
- includes/bp-groups/classes/class-bp-rest-attachments-group-cover-endpoint.php
- includes/bp-groups/classes/class-bp-rest-group-invites-endpoint.php
- includes/bp-groups/classes/class-bp-rest-group-membership-endpoint.php
- includes/bp-groups/classes/class-bp-rest-group-membership-request-endpoint.php
- includes/bp-groups/classes/class-bp-rest-groups-endpoint.php
- includes/bp-members/classes/class-bp-rest-attachments-member-avatar-endpoint.php
- includes/bp-members/classes/class-bp-rest-attachments-member-cover-endpoint.php
- includes/bp-members/classes/class-bp-rest-members-endpoint.php
- includes/bp-members/classes/class-bp-rest-signup-endpoint.php
- includes/bp-messages/classes/class-bp-rest-messages-endpoint.php
- includes/bp-notifications/classes/class-bp-rest-notifications-endpoint.php
- includes/bp-xprofile/classes/class-bp-rest-xprofile-data-endpoint.php
- includes/bp-xprofile/classes/class-bp-rest-xprofile-field-groups-endpoint.php
- includes/bp-xprofile/classes/class-bp-rest-xprofile-fields-endpoint.php
- package-lock.json
- package.json
- tests/activity/test-controller.php
- tests/members/test-controller.php
- tests/membership/test-group-membership-controller.php
- tests/multisite.xml
- tests/signup/test-controller.php
fixes #225 
- Cache schema from REST controllers
- Update schema cache hook param
-  Unit tests are running on all endpoints on multisite
- Skipped some tests on multisite (they require more investigation)
- Removing the `embed` context for consistency
- Added unit test for a member without an avatar
- updated `@wordpress/env` from its temporary url to the latest version: 4.0
> Caching schema in REST controllers

- includes/bp-activity/classes/class-bp-rest-activity-endpoint.php
- includes/bp-blogs/classes/class-bp-rest-blogs-endpoint.php
- includes/bp-groups/classes/class-bp-rest-group-membership-endpoint.php
- includes/bp-groups/classes/class-bp-rest-groups-endpoint.php
- includes/bp-members/classes/class-bp-rest-members-endpoint.php
- tests/activity/test-controller.php
- tests/blogs/test-controller.php
- tests/groups/test-controller.php
- tests/members/test-controller.php
- tests/membership/test-group-membership-controller.php
fixes #393 
- Components were reviewed so that their `prepare_links` were correct
- Missing objects were added
- Some had their keys changed to better reflect what they are
- Embedable componets had their schema context updated (@imath it's important to review which fields **should not** be available when embedding an object)
> Reviewing Components Prepare Links

- bp-rest.php
- readme.txt
BuddyPress 8.0.0 was just released. FYI I’ve just created a 0.4 branch for it.
New `@since` in docblocks for 0.5.0 will be `9.0.0` 😉
> Bump plugin version to 0.5.0

- includes/bp-blogs/classes/class-bp-rest-blogs-endpoint.php
Had a chance to use the `blogs` endpoint and noticed that the site avatar was always using the admin user's avatar instead of the site icon.
This PR fixes this by removing the `'user_id'` parameter from `bp_get_blog_avatar()`, which allows the proper site avatar to be used.
> Blogs: Remove user ID from avatar lookup

- includes/bp-activity/classes/class-bp-rest-activity-endpoint.php
- includes/bp-blogs/classes/class-bp-rest-blogs-endpoint.php
- includes/bp-friends/classes/class-bp-rest-friends-endpoint.php
- includes/bp-groups/classes/class-bp-rest-group-invites-endpoint.php
- includes/bp-groups/classes/class-bp-rest-group-membership-endpoint.php
- includes/bp-groups/classes/class-bp-rest-group-membership-request-endpoint.php
- includes/bp-groups/classes/class-bp-rest-groups-endpoint.php
- includes/bp-notifications/classes/class-bp-rest-notifications-endpoint.php
- includes/bp-xprofile/classes/class-bp-rest-xprofile-data-endpoint.php
Now [r12985](https://buddypress.trac.wordpress.org/changeset/12985) has been committed to BuddyPress trunk, we need to now use `bp_rest_get_object_url()` instead.
> Stop using the deprecated `bp_rest_get_user_url()` function

- includes/bp-members/classes/class-bp-rest-members-endpoint.php
- tests/members/test-controller.php
- tests/membership/test-group-membership-controller.php
This is needed by the Dynamic Members Widget block when filtering members according to their registration date (newest filter).
See https://github.com/buddypress/bp-blocks/blob/8ac19a789b1bc94c3aaca2a9834e68f96477066d/src/bp-members/js/dynamic-members.js#L75 for context.
> Add a new `registered_since` property to the Members schema

- includes/bp-groups/classes/class-bp-rest-groups-endpoint.php
- tests/groups/test-controller.php
This is needed by the Groups Dynamic Widget Block see [bp-blocks#52](https://github.com/buddypress/bp-blocks/pull/52/files#diff-28a91593413762c683a693126c2b9db73d07650c435d952f86136fea2f746e00R70)
> Add a new property `created_since` to the Groups item schema

- bp-rest.php
- includes/bp-messages/classes/class-bp-rest-sitewide-notices-endpoint.php
- tests/sitewide-notices/test-controller.php
Allow any logged-in user to fetch currently active notices that they haven't dismissed.
Allow any logged-in user to dismiss the currently active notice.
Allow site admins to create, fetch, and update sitewide notices.
> Add sitewide notices endpoint.

- includes/bp-messages/classes/class-bp-rest-sitewide-notices-endpoint.php
In the sitewide notices endpoint, in the action handler for
the "dismiss notice" endpoint, use the new core function
`bp_messages_dismiss_sitewide_notice()` to do the work.
> Use core function bp_messages_dismiss_sitewide_notice().

- README.md
- bp-rest.php
- readme.txt
I've just created https://github.com/buddypress/BP-REST/tree/0.5 for BuddyPress 9.0 branch
0.6.0 version will be included into BuddyPress 10.0.0
> Bump Plugin version to 0.6.0

- includes/bp-xprofile/classes/class-bp-rest-xprofile-data-endpoint.php
- tests/xprofile/test-data-controller.php
This was raised at https://buddypress.trac.wordpress.org/ticket/8537
Currently, if you pass an `array` with values and your XProfile field does not acccept multiple default values, we pass the value to `preg_split` which accepts a `string` not an `array`.
Note: if you pass a `string` value to a field that supports an `array`, we turn that `string` into an `array` of values. This is so that REST API users can add value such as `field value`, or `value1,value2,value3` and the endpoint will be smart enough to update it correctly in BuddyPress.
This was fixed in this pull request and unit test coverage was also improved.
> XProfile: Update Checkbox field type properly

- includes/bp-activity/classes/class-bp-rest-activity-endpoint.php
- includes/bp-groups/classes/class-bp-rest-groups-endpoint.php
- tests/activity/test-controller.php
Issue raised at https://buddypress.trac.wordpress.org/ticket/8524
When creating a group activity, `groups_post_update` needs a `group_id` but the rest of the `create_item` and `update_item` actions need a `item_id`, which was missing.
> Groups: when creating a group activity, save the item_id correctly

- .github/workflows/unit-tests.yml
- tests/groups/test-controller.php
Use the BP unit test factory to create the user. This is needed due to the change introduce in BuddyPress 10.0.0 about how the total group member count is calculated. See `BP_Groups_Group::get_total_member_count()` in  [13103](https://buddypress.trac.wordpress.org/changeset/13103/).
See #426
> Fix failing `BP_Test_REST_Group_Endpoint::test_get_items_extra()` test

- README.md
- composer.json
- composer.lock
- includes/bp-activity/classes/class-bp-rest-activity-endpoint.php
- includes/bp-blogs/classes/class-bp-rest-blogs-endpoint.php
- includes/bp-friends/classes/class-bp-rest-friends-endpoint.php
- includes/bp-groups/classes/class-bp-rest-group-invites-endpoint.php
- includes/bp-groups/classes/class-bp-rest-groups-endpoint.php
- includes/bp-members/classes/class-bp-rest-members-endpoint.php
- includes/bp-members/classes/class-bp-rest-signup-endpoint.php
- includes/bp-messages/classes/class-bp-rest-messages-endpoint.php
- includes/bp-messages/classes/class-bp-rest-sitewide-notices-endpoint.php
- includes/bp-xprofile/classes/class-bp-rest-xprofile-data-endpoint.php
- includes/bp-xprofile/classes/class-bp-rest-xprofile-fields-endpoint.php
- package-lock.json
- package.json
- phpcs.xml.dist
- tests/bootstrap.php
- Upgrading the `wp-env` package
- `yoast/phpunit-polyfills` introduced
- `wp-phpunit/wp-phpunit` upgraded to `5.8`
- Updating `package.json` to check current node version before moving forward.
- Fixing the last PHPCS issue
- Updating readme.md
- Updating WordPress version (related https://buddypress.trac.wordpress.org/ticket/8571)
> Updates: packages, PHPCs, etc

- includes/bp-xprofile/classes/class-bp-rest-xprofile-data-endpoint.php
- tests/xprofile/test-data-controller.php
fixes #424 
I'm suggesting we change the `value` type from an `array` into a `string`. The current behavior using an `array` is changing the output from `Option 01` into `["Option", "01"]`. Solving this for all use cases is tricky.
Instead of an `array` people would set the value as `Option 01,Option 02` which would be translated to an `array` in the REST API. This also would work for both single fields and fields with multiple options.
Other fixes:
- Unit tests support for the XProfile data update improved
- Clearing selected items of a field was introduced (a bug)
- Saving an option that a field does not have in its list of options returns an error
> XProfile Data: changing value type to a `string` instead of an `array`

- bp-rest.php
- readme.txt
0.7 will be included into BuddyPress 11.0.0
I've just created the [0.6](https://github.com/buddypress/BP-REST/tree/0.6) branch to use it into the BuddyPress 10.0 branch Grunt file.
> Bump plugin version to 0.7

- includes/bp-components/classes/class-bp-rest-components-endpoint.php
As titled.
Bug reported here: https://buddypress.org/support/topic/fatal-error-after-updating-to-php-8-0/
> Components: check if the `core` component is in the `array`

- includes/bp-members/classes/class-bp-rest-members-endpoint.php
To get the Activity Author's display name, when making an `activity/?_embed=true` request, we need to add the `embed` context to the `name` property of the members endpoint schema.
Fixes #458
> Add the `embed` context to the `name`’s members endpoint schema property

- includes/bp-activity/classes/class-bp-rest-activity-endpoint.php
- tests/testcases/activity/test-controller.php
Group Admin or Group Mod is firstly a group member, we just need to check whether a member is a member of a private/hidden group to allow hidden activities to be fetched.
I also think we should provide a filter to eventually allow third party component to manage hidden activities.
I've been looking at this part because I got an error having the `groups` component inactive and trying to get activity comments using `activity` as the component attribute. Problem was, when the `groups` component is not active, `buddypress()->groups->id is also not set.
> Simplify the group membership check into the Activity controller

- includes/bp-messages/classes/class-bp-rest-messages-endpoint.php
- tests/testcases/messages/test-controller.php
Make sure we return a proper `array` so that the output is consistent with the rest of the endpoints.
> Thread: update recipients `array`

- includes/bp-members/classes/class-bp-rest-members-endpoint.php
- tests/testcases/members/test-controller.php
This is a follow up of https://buddypress.trac.wordpress.org/ticket/8758
After more research, we haven't implemented this method yet. WordPress is kind of "faking" this method as it requires the user to have the `delete_users` capability which regular users don't. As we allow users to delete their account from the front-end, we should also allow users to delete their account using the BP REST API.
Ideally, I'd like this to be committed before we release BuddyPress 11.0.0 (~ December 14)
> Implement the `BP_REST_Members_Endpoint::delete_current_item()` method

- includes/bp-xprofile/classes/class-bp-rest-xprofile-field-groups-endpoint.php
- includes/bp-xprofile/classes/class-bp-rest-xprofile-fields-endpoint.php
- tests/testcases/xprofile/test-field-controller.php
- tests/testcases/xprofile/test-group-controller.php
The `profile_group_id` parameter of `BP_XProfile_Group::get()` now accepts (BuddyPress 11.0.0) an array of profile group ids. Instead of modifying the `profile_group_id` parameter of the collection params, I suggest to introduce an `include_groups` one.
See https://buddypress.trac.wordpress.org/changeset/13358/
> Adds a new collection parameter to include a list of profile fields groups

- includes/bp-members/classes/class-bp-rest-members-endpoint.php
- includes/bp-messages/classes/class-bp-rest-messages-endpoint.php
- tests/testcases/members/test-controller.php
- tests/testcases/membership/test-group-membership-controller.php
- tests/testcases/messages/test-controller.php
This function was deprecated in BuddyPress 12.0 and replaced by `bp_members_get_user_url()`.
See #479
> Stop using `bp_core_get_user_domain()` function

- includes/bp-blogs/classes/class-bp-rest-blogs-endpoint.php
- includes/bp-groups/classes/class-bp-rest-groups-endpoint.php
- tests/testcases/groups/test-controller.php
- Replace `bp_get_root_domain()` in favor of `bp_get_root_url()`
- Replace `bp_get_group_permalink()` in favor of `bp_get_group_url()`
See #479
> Use BP Rewrites ready functions to get blog/group links

- .github/workflows/unit-tests.yml
- composer.json
- Update composer.json file to use wp-phpunit 6.2
> Update GH PHPUnit action raising WP version to 6.2

- includes/bp-messages/classes/class-bp-rest-messages-endpoint.php
- tests/testcases/messages/test-controller.php
Instead of applying `wp_staticize_emoji` to subject and content which was ending up being stripped by the `wp_filter_kses` callback applied to the message subject template, move `wp_staticize_emoji` use inside BuddyPress core as a Messages filter.
See https://github.com/buddypress/buddypress/pull/123
Fixes #485
> Make sure the Message rendered subject uses WP Emojis

- .wp-env.json
- tests/testcases/xprofile/test-data-controller.php
Ticket: https://buddypress.trac.wordpress.org/ticket/9127
Applying this fix: https://github.com/buddypress/buddypress/pull/268
> XProfile field: test string with apostrophes is handled correctly in a field update

- includes/bp-messages/classes/class-bp-rest-messages-endpoint.php
> PHP Warning: Attempt to read property "display_name" on bool in /wp-content/plugins/buddypress/bp-messages/classes/class-bp-rest-messages-endpoint.php on line 879.
If the user query fails, one can get this PHP warning even though it returns an empty string due to the PHP typecasting.
So let's avoid this one warning.
Tickets:
- https://buddypress.trac.wordpress.org/ticket/9127
- https://buddypress.trac.wordpress.org/ticket/9133
> Messages: avoid a PHP Warning when getting a recipient's `display_name`

- includes/bp-members/classes/class-bp-rest-signup-endpoint.php
- tests/testcases/signup/test-controller.php
Pending:
---
Ticket: https://buddypress.trac.wordpress.org/ticket/8977
fixes #490
> Signup: Ability to resend activation email

- bp-rest.php
- includes/bp-activity/classes/class-bp-rest-activity-endpoint.php
- includes/bp-notifications/classes/class-bp-rest-notifications-endpoint.php
- phpunit.xml.dist
Steps to reproduce the DB error:
- Use a regular WP config (not Multisite)
- Activate Activity component if not already active 
- Activate the Blogs component if not already active
- Publish a new post (it should generate a `new_blog_post` activity
- Go to `buddypress/v1/activity?_embed=1` 
You should get the DB Error, I believe you can also get it trying to get the root blog using the corresponding endpoint.
I believe it’s only impacting the BP REST plugin as the Blogs REST Controller is only loaded when Multisite is active and a stable BuddyPress release is used. See https://github.com/buddypress/buddypress/blob/ef9fde9191b87a2f6a4027f2ecc75cfc1c616090/src/bp-blogs/classes/class-bp-blogs-component.php#L508
> Fix a DB Error when BP Blogs component is active on a regular WP

- bp-rest.php
- composer.json
- includes/bp-attachments/classes/trait-attachments.php
- includes/bp-friends/classes/class-bp-rest-friends-endpoint.php
- includes/bp-groups/classes/class-bp-rest-group-invites-endpoint.php
- includes/bp-groups/classes/class-bp-rest-groups-endpoint.php
- includes/bp-members/classes/class-bp-rest-members-endpoint.php
- includes/bp-members/classes/class-bp-rest-signup-endpoint.php
- includes/bp-messages/classes/class-bp-rest-sitewide-notices-endpoint.php
- includes/bp-notifications/classes/class-bp-rest-notifications-endpoint.php
- includes/bp-xprofile/classes/class-bp-rest-xprofile-fields-endpoint.php
- phpcs.xml.dist
ticket: https://buddypress.trac.wordpress.org/ticket/7228
> Support WPCS 3.0

- includes/bp-messages/classes/class-bp-rest-messages-endpoint.php
- tests/testcases/messages/test-controller.php
Initially, at #429, we added support for message pagination while listing threads. In this pr, we add support when getting a single thread, and its messages.
fixes #409 
Ticket: https://buddypress.trac.wordpress.org/ticket/9146
> Messages: add support for paginating thread messages

- includes/bp-activity/classes/class-bp-rest-activity-endpoint.php
- includes/bp-blogs/classes/class-bp-rest-attachments-blog-avatar-endpoint.php
- includes/bp-blogs/classes/class-bp-rest-blogs-endpoint.php
- includes/bp-groups/classes/class-bp-rest-attachments-group-avatar-endpoint.php
- includes/bp-groups/classes/class-bp-rest-attachments-group-cover-endpoint.php
- includes/bp-groups/classes/class-bp-rest-group-invites-endpoint.php
- includes/bp-groups/classes/class-bp-rest-group-membership-request-endpoint.php
- includes/bp-members/classes/class-bp-rest-attachments-member-avatar-endpoint.php
- includes/bp-members/classes/class-bp-rest-attachments-member-cover-endpoint.php
- includes/bp-members/classes/class-bp-rest-members-endpoint.php
- includes/bp-members/classes/class-bp-rest-signup-endpoint.php
- includes/bp-xprofile/classes/class-bp-rest-xprofile-field-groups-endpoint.php
- tests/bootstrap.php
- tests/testcases/activity/test-controller.php
- tests/testcases/attachments/test-blog-avatar-controller.php
- tests/testcases/attachments/test-group-avatar-controller.php
- tests/testcases/attachments/test-group-cover-controller.php
- tests/testcases/attachments/test-member-avatar-controller.php
- tests/testcases/attachments/test-member-cover-controller.php
- tests/testcases/blogs/test-controller.php
- tests/testcases/groups/test-controller.php
- tests/testcases/groups/test-group-invites-controller.php
- tests/testcases/members/test-controller.php
- tests/testcases/membership/test-group-membership-controller.php
- tests/testcases/membership/test-group-membership-request-controller.php
- tests/testcases/xprofile/test-data-controller.php
- tests/testcases/xprofile/test-field-controller.php
- tests/testcases/xprofile/test-group-controller.php
- fixes #496 
- adds unit tests
- add support for missing components, i.e., activity
> Review the `bp_view` capability support in endpoints

- includes/bp-groups/classes/class-bp-rest-group-membership-endpoint.php
Working on https://buddypress.trac.wordpress.org/ticket/9158 I realized using `BP_Groups_Member->$action()` methods was not a great idea. We really need to use `groups_$action_member()` functions instead.
In https://github.com/buddypress/buddypress/pull/293 I'm updating these functions so that it's possible to use them from the REST API (the `bp_is_item_admin()` checks were restricting their use to the Web).
This makes sure cache is cleared, group activities are removed when needed etc...
See: https://github.com/buddypress/buddypress/blob/edd1d2e33a2a4d3ace8216e06ba846a36f452b88/src/bp-groups/bp-groups-cache.php#L391|L394
> Use `groups_$action_member()` function to manage memberships

- includes/bp-groups/classes/class-bp-rest-group-membership-endpoint.php
- tests/testcases/membership/test-group-membership-controller.php
Ticket: https://buddypress.trac.wordpress.org/ticket/9163
> Admin cannot be demoted or removed from a group when he's the only one left
