buddypress/BP-REST

README.md
Added some more links, improved (a bit) formatting.
=> Readme further minor changes

package.json
• Use spaces not tabs for indentation
• Add repository type and URL
• Use valid SPDX license type
• Add keywords
• Add homepage and bugs URL's
• Use semantic versioning NPM packagage versions
=> Use a valid `package.json` file:

includes/bp-activity/classes/class-bp-activity-endpoints.php
Hook up collection options into get_items()
=> Activity GET endpoints

includes/bp-activity/classes/class-bp-activity-endpoints.php, includes/bp-activity/classes/class-bp-rest-activity-endpoint.php, includes/bp-groups/classes/class-bp-rest-groups-endpoint.php
=> Activity endpoint - DELETE

includes/bp-activity/classes/class-bp-activity-endpoints.php, includes/bp-activity/classes/class-bp-rest-activity-controller.php
I have registered route to add a new activity.
=> Activity endpoint - CREATE

includes/bp-activity/classes/class-bp-rest-activity-endpoint.php
=> Prepare response to display threaded comments

bp-rest.php, includes/bp-xprofile/classes/class-bp-xprofile-fields-endpoints.php, includes/bp-xprofile/classes/class-bp-xprofile-groups-endpoints.php
Add basic support for fetching information about xprofile field groups.
Uses the parameters available to `BP_XProfile_Group::get()`.
=> Add GET support for xprofile groups.

includes/bp-notifications/classes/class-bp-rest-notifications-endpoint.php, tests/notifications/test-controller.php
This PR updates the notification endpoint to update a notification marking it as read or unread.
=> Notifications: Update Support

.gitignore, .travis.yml, bin/test.sh, composer.json, tests/bootstrap.php
i think this will fix the failing TravisCI build - opening a PR so that we can get a build running
=> Install correct version of PHP on Travis.

includes/bp-activity/classes/class-bp-rest-activity-endpoint.php
This changeset moves the fetching of user activities out of an
unrelated permission check. See #99. It also reduces overhead by
only querying the database for user favorites when they're needed.
=> Fetch user activities only when needed.

includes/bp-activity/classes/class-bp-rest-activity-endpoint.php
=> Query activity items regardless of spam status

includes/bp-activity/classes/class-bp-rest-activity-endpoint.php, includes/bp-groups/classes/class-bp-rest-groups-endpoint.php, includes/bp-messages/classes/class-bp-rest-messages-endpoint.php, includes/bp-notifications/classes/class-bp-rest-notifications-endpoint.php, includes/bp-xprofile/classes/class-bp-rest-xprofile-fields-endpoint.php, includes/bp-xprofile/classes/class-bp-rest-xprofile-groups-endpoint.php
=> Adding ability to filter the query args of the get_items queries

includes/bp-activity/classes/class-bp-rest-activity-endpoint.php, includes/bp-messages/classes/class-bp-rest-messages-endpoint.php, tests/activity/test-controller.php
=> "primary_association" New Naming

includes/bp-activity/classes/class-bp-rest-activity-endpoint.php, tests/activity/test-controller.php
=> Transparent Params for Activity Queries

README.md, bp-rest.php, includes/bp-groups/classes/class-bp-rest-group-members-endpoint.php, includes/bp-groups/classes/class-bp-rest-groups-endpoint.php, includes/bp-groups/classes/class-bp-rest-groups-members-endpoint.php, includes/bp-members/classes/class-bp-rest-members-endpoint.php, includes/functions.php, tests/groups/test-group-member-controller.php
=> Group Membership Endpoint

includes/bp-activity/classes/class-bp-rest-activity-endpoint.php, includes/bp-groups/classes/class-bp-rest-group-members-endpoint.php, includes/bp-groups/classes/class-bp-rest-groups-endpoint.php, includes/bp-members/bp-members-filters.php, includes/bp-members/classes/class-bp-rest-members-endpoint.php, includes/bp-messages/classes/class-bp-rest-messages-endpoint.php, includes/bp-notifications/classes/class-bp-rest-notifications-endpoint.php, includes/bp-xprofile/classes/class-bp-rest-xprofile-fields-endpoint.php, includes/bp-xprofile/classes/class-bp-rest-xprofile-groups-endpoint.php, includes/functions.php, tests/activity/test-controller.php, tests/groups/test-controller.php, tests/groups/test-group-member-controller.php, tests/members/test-controller.php, tests/notifications/test-controller.php, tests/xprofile/test-field-controller.php, tests/xprofile/test-group-controller.php
=> Allow Filtering of BuddyPress Namespace

README.md, bp-rest.php, includes/bp-groups/classes/class-bp-rest-group-invites-endpoint.php, includes/bp-groups/classes/class-bp-rest-group-members-endpoint.php, tests/groups/test-group-invites-controller.php, tests/groups/test-group-member-controller.php
Implementation of the group invitations.
This is ready for code review.
=> Group Invitation Endpoints

README.md, bp-rest.php, includes/bp-xprofile/classes/class-bp-rest-xprofile-data-endpoint.php, includes/bp-xprofile/classes/class-bp-rest-xprofile-fields-endpoint.php, includes/functions.php, tests/xprofile/test-data-controller.php
=> XProfile Data Endpoints

README.md, bp-rest.php, includes/bp-components/classes/class-bp-rest-components-endpoint.php, tests/components/test-controller.php
=> Components Endpoints

README.md, bp-rest.php, includes/bp-activity/classes/class-bp-rest-activity-endpoint.php, includes/bp-components/classes/class-bp-rest-components-endpoint.php, includes/bp-groups/classes/class-bp-rest-group-invites-endpoint.php, includes/bp-groups/classes/class-bp-rest-group-membership-endpoint.php, includes/bp-groups/classes/class-bp-rest-groups-endpoint.php, includes/bp-members/classes/class-bp-rest-members-endpoint.php, includes/bp-messages/classes/class-bp-rest-messages-endpoint.php, includes/bp-notifications/classes/class-bp-rest-notifications-endpoint.php, includes/bp-xprofile/classes/class-bp-rest-xprofile-data-endpoint.php, includes/bp-xprofile/classes/class-bp-rest-xprofile-fields-endpoint.php, includes/bp-xprofile/classes/class-bp-rest-xprofile-groups-endpoint.php, includes/functions.php, tests/activity/test-controller.php, tests/groups/test-controller.php, tests/notifications/test-controller.php, tests/xprofile/test-group-controller.php
=> Schema and Collections Review

.travis.yml, includes/bp-activity/classes/class-bp-rest-activity-endpoint.php, includes/bp-groups/classes/class-bp-rest-group-invites-endpoint.php, includes/bp-groups/classes/class-bp-rest-group-membership-endpoint.php, includes/bp-groups/classes/class-bp-rest-groups-endpoint.php, includes/bp-members/classes/class-bp-rest-members-endpoint.php, includes/bp-messages/classes/class-bp-rest-messages-endpoint.php, includes/bp-notifications/classes/class-bp-rest-notifications-endpoint.php, includes/bp-xprofile/classes/class-bp-rest-xprofile-data-endpoint.php, includes/bp-xprofile/classes/class-bp-rest-xprofile-fields-endpoint.php, includes/bp-xprofile/classes/class-bp-rest-xprofile-groups-endpoint.php, includes/functions.php, tests/activity/test-controller.php, tests/components/test-controller.php, tests/groups/test-controller.php, tests/groups/test-group-invites-controller.php, tests/groups/test-group-membership-controller.php, tests/members/test-controller.php, tests/notifications/test-controller.php, tests/xprofile/test-data-controller.php, tests/xprofile/test-field-controller.php, tests/xprofile/test-group-controller.php
=> Unit tests coverage review

.travis.yml, README.md
=> Test BuddyPress Versions

bp-rest.php, includes/bp-activity/classes/class-bp-rest-activity-endpoint.php, includes/bp-components/classes/class-bp-rest-components-endpoint.php, includes/bp-groups/classes/class-bp-rest-group-invites-endpoint.php, includes/bp-groups/classes/class-bp-rest-group-membership-endpoint.php, includes/bp-groups/classes/class-bp-rest-groups-endpoint.php, includes/bp-members/classes/class-bp-rest-members-endpoint.php, includes/bp-messages/classes/class-bp-rest-messages-endpoint.php, includes/bp-notifications/classes/class-bp-rest-notifications-endpoint.php, includes/bp-xprofile/classes/class-bp-rest-xprofile-data-endpoint.php, includes/bp-xprofile/classes/class-bp-rest-xprofile-field-groups-endpoint.php, includes/bp-xprofile/classes/class-bp-rest-xprofile-fields-endpoint.php, tests/xprofile/test-group-controller.php
=> Endpoints Permissions Check Override

README.md, bp-rest.php, includes/bp-groups/classes/class-bp-rest-group-membership-endpoint.php, includes/bp-groups/classes/class-bp-rest-group-membership-request-endpoint.php, includes/bp-groups/classes/class-bp-rest-groups-endpoint.php, tests/groups/test-group-membership-controller.php, tests/groups/test-group-membership-request-controller.php
=> Request a Group Membership

includes/bp-messages/classes/class-bp-rest-messages-endpoint.php
This PR includes :
- fix get_items_permissions_check() so that users can read their messages
- fix a warning when a box is empty as in this case the `$messages_box->threads` is Null
- set the default box as the inbox
- starts improving the way a thread is prepared for response :
1. The subject, excerpt, and content should be sent in arrays containing raw and rendered values
2. Recipients should be included.
3. Add some @todos to not forget recipients avatars, names, links and the starred feature.
=> Improve the way private message threads are fetched

includes/bp-messages/classes/class-bp-rest-messages-endpoint.php, tests/messages/test-controller.php
=> Messages Endpoints

includes/bp-groups/classes/class-bp-rest-group-membership-request-endpoint.php, includes/bp-groups/classes/class-bp-rest-groups-endpoint.php, includes/bp-members/classes/class-bp-rest-members-endpoint.php, tests/members/test-controller.php, tests/membership/test-group-membership-controller.php, tests/membership/test-group-membership-request-controller.php
=> Remove exposure of email

Gruntfile.js, bp-rest.php, includes/functions.php, package-lock.json, package.json
I've found a missing textdomain and wanted to check all files quickly, that's why I've added Grunt. But you can only fix the missing text domain if you think Grunt is not needed ;)
=> Fix a missing text domain and add a Grunt Task to check textdomain

includes/bp-members/classes/class-bp-rest-members-endpoint.php
- The mention name or user login are not updatable.
- The password belongs to the Settings endpoint parameter.
- The mention name or user login are not updatable.
- The password belongs to the Settings endpoint parameter.
- Make sure it is possible to self update for a regular user
- Neutralize the `DELETE` transport method as it is specific to the User Settings component and it is not working anyway (even in WP REST API).
PS: The documentation for the [Members endpoint](https://imath-buddydocs.pf1.wpserveur.net/bp-rest-api/reference/members/) is finished!
=> Improve buddypress/v1/members/<id> & buddypress/v1/members/me routes

includes/bp-xprofile/classes/class-bp-rest-xprofile-field-groups-endpoint.php
1. Make sure the ID is listed as part of the params for the transport method of the `/buddypress/v1/xprofile/groups/<id>` route.
2. Edit the description type for CREATABLE and EDITABLE transport methods and make sure the group position can only be updated.
3. Make sure it is possible to update each property of a group of profile fields independently without deleting the other properties. For example only edit the name without resetting the description and can_delete properties.
4. Make it possible to update the position (group_order) of the Group of profile fields.
5. Improve the item schema descriptions replacing "object" by "group of profile fields".
NB: The [documentation about the Profile Groups](https://imath-buddydocs.pf1.wpserveur.net/bp-rest-api/reference/extended-profiles/profile- …
=> Improve arguments for the XProfile Groups endpoints & fix a bug

includes/bp-groups/classes/class-bp-rest-group-membership-endpoint.php
1. Make sure the group id is the first collection parameter of the `/buddypress/v1/groups/<group_id>/members` route.
2. Make sure the group id and the user id are the first arguments of the `/buddypress/v1/groups/<group_id>/members/<user_id>` routes
3. Replace the `get_update_collection_params()` method by the `get_endpoint_args_for_method()` method and make sure this one only gets the needed arguments for the corresponding Transport Method.
4. Make sure a just created member who was directly promoted during this creation generates a response containing the right group role properties.
5. Improve the item schema properties.
The [Group Membership endpoint's documentation](https://imath-buddydocs.pf1.wpserveur.net/bp-rest-api/reference/user-groups/group-membership/) has been written, taking …
=> Improve the Group Membership endpoint arguments

tests/membership/test-group-membership-controller.php
=> Improve the unit test checking the endpoint for a user to join a group

includes/bp-groups/classes/class-bp-rest-group-invites-endpoint.php, includes/bp-groups/classes/class-bp-rest-group-membership-request-endpoint.php
Looks like PHPCS on Travis missed some 🤔
=> Improve code formatting for the Group membership requests & invites controllers

includes/bp-activity/classes/class-bp-rest-activity-endpoint.php, includes/bp-attachments/classes/class-bp-rest-attachments-group-avatar-endpoint.php, includes/bp-attachments/classes/class-bp-rest-attachments-member-avatar-endpoint.php, includes/bp-components/classes/class-bp-rest-components-endpoint.php, includes/bp-groups/classes/class-bp-rest-group-invites-endpoint.php, includes/bp-groups/classes/class-bp-rest-group-membership-endpoint.php, includes/bp-groups/classes/class-bp-rest-group-membership-request-endpoint.php, includes/bp-groups/classes/class-bp-rest-groups-endpoint.php, includes/bp-members/classes/class-bp-rest-members-endpoint.php, includes/bp-messages/classes/class-bp-rest-messages-endpoint.php, includes/bp-notifications/classes/class-bp-rest-notifications-endpoint.php, includes/bp-xprofile/classes/class-bp-rest-xprofile-data-endpoint.php, includes/bp-xprofile/classes/class-bp-rest-xprofile-field-groups-endpoint.php, includes/bp-xprofile/classes/class-bp-rest-xprofile-fields-endpoint.php, tests/membership/test-group-membership-controller.php, tests/membership/test-group-membership-request-controller.php
=> Adding context for POST and PUT requests

bp-rest.php, includes/bp-attachments/classes/class-bp-rest-attachments-group-cover-endpoint.php, includes/bp-attachments/classes/class-bp-rest-attachments-member-avatar-endpoint.php, includes/bp-attachments/classes/trait-attachments.php, tests/attachments/test-group-cover-controller.php, tests/attachments/test-member-avatar-controller.php
=> Group Cover Endpoints

.travis.yml, README.md, bp-rest.php, includes/bp-blogs/classes/class-bp-rest-blogs-endpoint.php, tests/blogs/test-controller.php, tests/multisite.xml
=> Blogs endpoints

tests/blogs/test-controller.php
You were right.
I was looking for the functions that add/update values to additional fields and couldn't find them. But that's logical! As there are no create/update methods and we only get items in this controller, there can't be such functions used :)
I just suggest to add this unit test to be sure Blogs rest fields are fetched.
PS: as BuddyPress is handling blog signups, I'm wondering if we should include a create item method. I'll think about it and will get back to you if it's needed.
Fixes #246
=> Add a unit test for additional fields

README.md, bp-rest.php, includes/bp-attachments/classes/class-bp-rest-attachments-member-cover-endpoint.php, includes/bp-attachments/classes/trait-attachments.php, includes/bp-members/classes/class-bp-rest-members-endpoint.php, tests/attachments/test-member-cover-controller.php
=> Members Cover Endpoints

includes/bp-groups/classes/class-bp-rest-group-membership-endpoint.php
=> Group Membership Schema Type Mismatch

includes/bp-friends/classes/class-bp-rest-friends-endpoint.php, tests/friends/test-controller.php
=> Adding missing args for the request friendship endpoint

includes/bp-groups/classes/class-bp-rest-group-membership-endpoint.php, tests/membership/test-group-membership-controller.php
=> Making sure one can only add himself to a group

includes/bp-activity/classes/class-bp-rest-activity-endpoint.php, tests/activity/test-controller.php
=> Activity Scopes

.travis.yml, phpcs.xml
Checking phpcs via a file rather than manually on the command line.
=> PHPCS File

includes/bp-members/classes/class-bp-rest-members-endpoint.php, tests/members/test-controller.php, tests/membership/test-group-membership-controller.php
=> Output friendship status in a user/member response

includes/bp-groups/classes/class-bp-rest-groups-endpoint.php, includes/bp-members/classes/class-bp-rest-members-endpoint.php, tests/groups/test-controller.php, tests/members/test-controller.php
=> Setting group/member types

includes/bp-activity/classes/class-bp-rest-activity-endpoint.php
=> Return an error while trying to get an invalid activity item

bp-rest.php, includes/bp-attachments/classes/class-bp-rest-attachments-group-avatar-endpoint.php, includes/bp-attachments/classes/trait-attachments.php, includes/functions.php, tests/attachments/test-group-avatar-controller.php, tests/attachments/test-group-cover-controller.php, tests/attachments/test-member-avatar-controller.php, tests/attachments/test-member-cover-controller.php
Updating attachments implementation to account for the move from the XProfile to the Members component.
=> Update Attachments implementation

includes/bp-messages/classes/class-bp-rest-messages-endpoint.php, tests/messages/test-controller.php
=> Messages: create_item hook

includes/bp-friends/classes/class-bp-rest-friends-endpoint.php, tests/friends/test-controller.php
=> Friendship Improvements

includes/bp-friends/classes/class-bp-rest-friends-endpoint.php, tests/friends/test-controller.php
=> Avoiding regular users from creating friendships to others

.editorconfig, .gitignore, .travis.yml, composer.json, composer.lock, includes/bp-attachments/classes/trait-attachments.php, includes/bp-blogs/classes/class-bp-rest-attachments-blog-avatar-endpoint.php, includes/bp-blogs/classes/class-bp-rest-blogs-endpoint.php, includes/bp-components/classes/class-bp-rest-components-endpoint.php, includes/bp-friends/classes/class-bp-rest-friends-endpoint.php, includes/bp-groups/classes/class-bp-rest-attachments-group-avatar-endpoint.php, includes/bp-groups/classes/class-bp-rest-attachments-group-cover-endpoint.php, includes/bp-members/classes/class-bp-rest-attachments-member-avatar-endpoint.php, includes/bp-members/classes/class-bp-rest-signup-endpoint.php, includes/bp-notifications/classes/class-bp-rest-notifications-endpoint.php, includes/bp-xprofile/classes/class-bp-rest-xprofile-data-endpoint.php, package-lock.json, package.json, phpcs.xml.dist, readme.txt, tests/components/test-controller.php, tests/signup/test-controller.php
**No changes to functionality,** only improving unit tests and removing lots of things that are honestly not needed.
=> Cleaning up

includes/bp-members/classes/class-bp-rest-signup-endpoint.php, tests/signup/test-controller.php
- Improve schema in case of Multisite config (prefix all arguments related to site with `site` to avoid confusions).
- Activation should use the Activation key.
- No need to be an admin or logged in to sign up, registration is open to everyone.
- Use available signup validation function and hooks to make sure to avoid duplicates and to send the notification emails when needed.
These improvements are really needed. I must confess I thought about removing this endpoint from the 6.0.0 release because I felt it was very risky to bypass WordPress & BuddyPress registration process/signup validations the way it was before. It took my sunday reviewing everything and I believe it's better now.
Thanks for your review/feedback.
=> Make sure the Signup Endpoint is more inline with the registration process

includes/bp-members/classes/class-bp-rest-members-endpoint.php, tests/members/test-controller.php, tests/membership/test-group-membership-controller.php
=> Friendship status slug in the member response

includes/bp-friends/classes/class-bp-rest-friends-endpoint.php, tests/friends/test-controller.php
The conditional verifies if there is already a friendship request or if the users are already friends.
fixes #321
=> Adding a conditional before requesting friendship

includes/bp-friends/classes/class-bp-rest-friends-endpoint.php
=> Backport PR #328 to 0.2 branch

includes/bp-groups/classes/class-bp-rest-groups-endpoint.php
When updating a group, for the fields that are not being updated, fallback to the their value.
fixes #319
=> Group update fix

includes/bp-members/classes/class-bp-rest-members-endpoint.php, tests/members/test-controller.php
=> Single member item permission checks

.travis.yml
This is not a big deal. Mainly to validate the Travis config.
=> Travis config keys warnings

includes/bp-attachments/classes/trait-attachments.php
https://buddypress.trac.wordpress.org/ticket/8336
=> Attachments fix for those on Windows/WAMP installs

includes/bp-activity/classes/class-bp-rest-activity-endpoint.php, tests/activity/test-controller.php
=> Get activities using more than one type

includes/bp-activity/classes/class-bp-rest-activity-endpoint.php, includes/bp-members/classes/class-bp-rest-members-endpoint.php
=> Set `last_activity` when creating an activity

README.md, includes/bp-blogs/classes/class-bp-rest-blogs-endpoint.php, tests/blogs/test-controller.php
=> Creating a new BuddyPress Blog

includes/bp-groups/classes/class-bp-rest-groups-endpoint.php, tests/groups/test-controller.php
Working on the BP Groups block, I needed to get some extra information about the group. As the number of members and the last activity are displayed on the front end publicly I believe we can safely fetch these pieces of information even if not into the edit context.
=> Use a `populate_extras` query arg to get group/s number of members & last activity

includes/bp-friends/classes/class-bp-rest-friends-endpoint.php, tests/friends/test-controller.php
=> Friends: Fail for user creating friendship requests to themselves

includes/bp-notifications/classes/class-bp-rest-notifications-endpoint.php, tests/notifications/test-controller.php
Related to #367 
This adds support to the `user_ids` so that one can fetch notifications from more than one person.
=> Notifications Improvements

.gitignore, includes/bp-members/classes/class-bp-rest-members-endpoint.php
=> Members: Preserve order of XProfile groups/fields

.wp-env.json, readme.txt, tests/define-constants.php, tests/groups/test-controller.php
=> Unit tests: improving unit tests support

composer.lock, includes/bp-members/classes/class-bp-rest-members-endpoint.php
See https://buddypress.trac.wordpress.org/ticket/8472
If no search terms were requested, we need to set the argument to false.
=> Avoid SQL overheat into the Members get_items endpoint

includes/bp-notifications/classes/class-bp-rest-notifications-endpoint.php, tests/notifications/test-controller.php
=> Notifications: notification does not return an invalid object

includes/bp-activity/classes/class-bp-rest-activity-endpoint.php
=> Activity: updating controller to fetch params properly

includes/bp-blogs/classes/class-bp-rest-attachments-blog-avatar-endpoint.php, includes/bp-blogs/classes/class-bp-rest-blogs-endpoint.php, includes/bp-components/classes/class-bp-rest-components-endpoint.php, includes/bp-friends/classes/class-bp-rest-friends-endpoint.php, includes/bp-messages/classes/class-bp-rest-messages-endpoint.php, includes/bp-notifications/classes/class-bp-rest-notifications-endpoint.php
=> Several components: updating controller to fetch params properly

includes/bp-components/classes/class-bp-rest-components-endpoint.php, tests/components/test-controller.php
So far BP Blocks used WP Block Editor settings filters to get components active features. With the introduction of the Widget Block Editor, it appears it’s not a so great choice. Getting these features from blocks is a pain as they are not available from the same WP Core store. I believe we need to use our own BP Core Store with everything we need inside it. That’s what I’ve done into the latest version of the BP Blocks plugin. So far I was using a custom REST API fields but I think this should benefit everyone once we can inform from this endpoint about the acive BP features for each component.
I’ve also added a new `is_active` property to the schema because developers cannot rely on the `status` property as it is a l10n string. The `is_active` property is a boolean and is a better way …
=> Improve the `BP_REST_Components_Endpoint` controller to inform about active component features

includes/bp-members/classes/class-bp-rest-members-endpoint.php
The WP REST API has a global `'_fields'` parameter allowing consumers of the API to restrict the response to only properties specified in `'_fields'`: https://developer.wordpress.org/rest-api/using-the-rest-api/global-parameters/#_fields
We should check this parameter before querying for any member properties in the `BP_REST_Members_Endpoint::user_data()` method: https://github.com/buddypress/BP-REST/blob/02d3de0ee278c52a80c2f77a272b9af1b079f4d6/includes/bp-members/classes/class-bp-rest-members-endpoint.php#L482
For example, if we perform the following BP Members API request: `example.com/wp-json/buddypress/v1/members/?_fields=id,name,user_login,link`, this shouldn't query other member fields like `'xprofile'`, `'friendship_status'`, etc. This can dramatically speed up the response time …
=> Members: Only query for fields when necessary

includes/bp-members/classes/class-bp-rest-signup-endpoint.php, tests/signup/test-controller.php
Removing activation key in the CREATE response.
=> Remove activation key from response

includes/bp-members/classes/class-bp-rest-members-endpoint.php, tests/members/test-controller.php
=> Update get_items xprofile parameter type

includes/bp-messages/classes/class-bp-rest-messages-endpoint.php, tests/messages/test-controller.php
fixes #409 
Related: https://buddypress.trac.wordpress.org/ticket/8597
The BP REST API Documentation will need to be updated as well.
=> Paginating Thread messages/recipients

includes/bp-groups/classes/class-bp-rest-groups-endpoint.php, tests/groups/test-controller.php
Improving groups unit tests, particularly related to the endpoint that get groups.
Related to #433
=> Groups: improving unit tests

includes/bp-activity/classes/class-bp-rest-activity-endpoint.php, includes/bp-blogs/classes/class-bp-rest-blogs-endpoint.php, includes/bp-friends/classes/class-bp-rest-friends-endpoint.php, includes/bp-groups/classes/class-bp-rest-group-invites-endpoint.php, includes/bp-groups/classes/class-bp-rest-group-membership-request-endpoint.php, includes/bp-groups/classes/class-bp-rest-groups-endpoint.php, includes/bp-members/classes/class-bp-rest-members-endpoint.php, includes/bp-members/classes/class-bp-rest-signup-endpoint.php, includes/bp-messages/classes/class-bp-rest-messages-endpoint.php, includes/bp-messages/classes/class-bp-rest-sitewide-notices-endpoint.php, includes/bp-notifications/classes/class-bp-rest-notifications-endpoint.php, includes/bp-xprofile/classes/class-bp-rest-xprofile-field-groups-endpoint.php
=> Add action links to items

composer.json, composer.lock, phpcs.xml.dist
=> PHPCS: Using BP ruleset

.github/workflows/unit-tests.yml, composer.json, package-lock.json, package.json, tests/testcases/attachments/test-group-avatar-controller.php, tests/testcases/attachments/test-group-cover-controller.php, tests/testcases/messages/test-controller.php
The requested user id is `$u1` as a result the `unread_count` of the thread is the one of this user. This change is due to the commit we made on BuddyPress SVN trac, see [[13339]](https://buddypress.trac.wordpress.org/changeset/13339/).
This commit also fixes a typo in the group avatar and group cover image unit tests.
=> Fix Messages endpoint failing PHPUnit test

bp-rest.php, readme.txt
0.8 will be included into BuddyPress 12.0.0
=> Bump plugin version to 0.8

package-lock.json, package.json, tests/bootstrap.php, tests/env-wp-phpunit-config.php
This is also updating simple git to 3.16.
Fixes #472
=> Update wp-env to latest version

includes/bp-components/classes/class-bp-rest-components-endpoint.php, tests/testcases/components/test-controller.php
See https://buddypress.org/support/topic/buddypress-11-1-0/#post-328604
This fix needs to be back-ported into 0.7 branch.
=> Fix a notice error in the Components controller

includes/bp-groups/classes/class-bp-rest-attachments-group-avatar-endpoint.php, includes/bp-groups/classes/class-bp-rest-attachments-group-cover-endpoint.php, includes/bp-groups/classes/class-bp-rest-group-membership-endpoint.php, includes/bp-groups/classes/class-bp-rest-groups-endpoint.php, includes/bp-members/classes/class-bp-rest-attachments-member-avatar-endpoint.php, includes/bp-members/classes/class-bp-rest-attachments-member-cover-endpoint.php, includes/bp-members/classes/class-bp-rest-members-endpoint.php, includes/bp-xprofile/classes/class-bp-rest-xprofile-data-endpoint.php, includes/bp-xprofile/classes/class-bp-rest-xprofile-field-groups-endpoint.php, includes/bp-xprofile/classes/class-bp-rest-xprofile-fields-endpoint.php
This new capability will work with the community visibility features coming in BuddyPress 12.
Trac ticket: https://buddypress.trac.wordpress.org/ticket/8734
=> Support the bp_view capability.

bp-rest.php, readme.txt
0.9.0 will be included in BuddyPress 14.0.0
=> Bump plugin version to 0.9.0

.editorconfig, .github/workflows/coding-standards.yml, .github/workflows/unit-tests.yml, .wp-env.json, composer.json, package.json, readme.txt
- `.editorconfig` reflects the version from BP core;
- ^ Format files using the new rules;
- Bump plugin version in the `readme.txt` file;
- Updates to Github Actions.
=> Misc changes: plugin updates

includes/bp-messages/classes/class-bp-rest-messages-endpoint.php, tests/testcases/messages/test-controller.php
Ticket: https://buddypress.trac.wordpress.org/ticket/9084
=> Messages: tests for the message star actions

includes/bp-members/classes/class-bp-rest-members-endpoint.php, includes/bp-members/classes/class-bp-rest-signup-endpoint.php, includes/bp-xprofile/classes/class-bp-rest-xprofile-field-groups-endpoint.php, includes/bp-xprofile/classes/class-bp-rest-xprofile-fields-endpoint.php, tests/testcases/signup/test-controller.php, tests/testcases/xprofile/test-data-controller.php
Ticket: https://buddypress.trac.wordpress.org/ticket/8976
fixes #489
=> Registration through REST API with additional profile fields

includes/bp-messages/classes/class-bp-rest-messages-endpoint.php, tests/testcases/messages/test-controller.php
Ticket: https://buddypress.trac.wordpress.org/ticket/9170
=> BP9170: "raw" property missing from subject/excerpt/message nodes
